### ISSUE TITLE
[Linux] compile_telemac.py does only compile the default config

### ISSUE THREAD

**Issue by tomsail** [nicogodet/telemac-mascaret-feedstock#7]
In `compile_telemac.py`, the version compiled is only the `USETELCFG` that is set at the beginning of build.sh
Whereas we should have all configs present in the `systel.cfg` file

**Comment by nicogodet** [comment]
That's weird because I compile TELEMAC on a Linux cluster in my company and not defining USETELCFG result in compiling all configs.

**Comment by tomsail** [comment]
that was the fix thanks

**Comment by tomsail** [comment]
fixed with #6
